// signing-config generates build inputs. Installed apps never read this config.
package main

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type config struct {
	TeamID       string `json:"team_id"`
	BundleID     string `json:"bundle_id"`
	SignIdentity string `json:"sign_identity,omitempty"`
	Profile      string `json:"profile,omitempty"`
}

var teamPattern = regexp.MustCompile(`^[A-Z0-9]{10}$`)
var bundlePattern = regexp.MustCompile(`^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$`)
var fingerprintPattern = regexp.MustCompile(`^[A-Fa-f0-9]{40}$`)

func readConfig(path string) (config, error) {
	var c config
	data, err := os.ReadFile(path)
	if err != nil {
		return c, err
	}
	d := json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&c); err != nil {
		return c, err
	}
	var extra any
	if err := d.Decode(&extra); !errors.Is(err, io.EOF) {
		return c, errors.New("설정 뒤에 추가 데이터가 있습니다")
	}
	return c, nil
}

func (c config) validate(mode string, official config) error {
	if !teamPattern.MatchString(c.TeamID) || !bundlePattern.MatchString(c.BundleID) || len(c.BundleID) > 200 {
		return errors.New("team_id는 영문 대문자·숫자 10자, bundle_id는 점으로 구분한 영문·숫자·하이픈이어야 합니다")
	}
	if strings.ContainsAny(c.SignIdentity+c.Profile, "\x00\r\n") {
		return errors.New("인증서 이름과 프로파일 경로에 제어 문자를 사용할 수 없습니다")
	}
	if c.SignIdentity != "" && !fingerprintPattern.MatchString(c.SignIdentity) && (!strings.HasPrefix(c.SignIdentity, "Developer ID Application: ") || !strings.HasSuffix(c.SignIdentity, " ("+c.TeamID+")")) {
		return errors.New("sign_identity는 같은 팀의 Developer ID Application 인증서 이름 또는 40자리 인증서 지문이어야 합니다")
	}
	if mode != "final" && mode != "migration" {
		return errors.New("PASU_RELEASE_MODE는 final 또는 migration이어야 합니다")
	}
	if mode == "migration" && (c.TeamID != official.TeamID || c.BundleID != official.BundleID) {
		return errors.New("구버전 그룹 이전은 기존 공식 Pasu 신원에서만 지원합니다")
	}
	return nil
}

func xmlText(s string) string {
	var b bytes.Buffer
	_ = xml.EscapeText(&b, []byte(s))
	return b.String()
}

func generate(root string, c config) error {
	agent := c.BundleID + ".agent"
	group := c.TeamID + "." + agent
	goSource, err := format.Source([]byte(fmt.Sprintf(`// Code generated by scripts/signing-config; DO NOT EDIT.
package main
const (
pasuTeamID = %q
pasuGUIIdentifier = %q
pasuAgentIdentifier = %q
)
`, c.TeamID, c.BundleID, agent)))
	if err != nil {
		return err
	}
	files := map[string][]byte{"signing_identity_generated.go": goSource}
	files[".build/signing/Identity.swift"] = []byte(fmt.Sprintf(`// Code generated by scripts/signing-config; DO NOT EDIT.
enum PasuIdentity {
    static let teamID = %q
    static let guiID = %q
    static let agentID = %q
    static let keychainService = guiID
    static let accessGroup = teamID + "." + agentID
}
`, c.TeamID, c.BundleID, agent))
	replacer := strings.NewReplacer("PASU_GUI_ID", c.BundleID, "PASU_AGENT_ID", agent, "PASU_ACCESS_GROUP", group, "PASU_TEAM_ID", c.TeamID)
	for _, name := range []string{"Info.plist", "Agent-Info.plist", "PasuAgent.plist", "Pasu.entitlements"} {
		data, err := os.ReadFile(filepath.Join(root, "packaging", name))
		if err != nil {
			return err
		}
		files[".build/signing/"+name] = []byte(replacer.Replace(string(data)))
	}
	files[".build/signing/settings.plist"] = []byte(fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0"><dict>
<key>TeamID</key><string>%s</string>
<key>GUIBundleID</key><string>%s</string>
<key>AgentBundleID</key><string>%s</string>
<key>Identity</key><string>%s</string>
<key>Profile</key><string>%s</string>
</dict></plist>
`, c.TeamID, c.BundleID, agent, xmlText(c.SignIdentity), xmlText(c.Profile)))
	for name, data := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
			return err
		}
		mode := os.FileMode(0644)
		if name == ".build/signing/settings.plist" {
			mode = 0600
		}
		if err := os.WriteFile(path, data, mode); err != nil {
			return err
		}
		if err := os.Chmod(path, mode); err != nil {
			return err
		}
	}
	return nil
}

func loadBuildConfig(root, path, identity, profile, mode string) (config, error) {
	official, err := readConfig(filepath.Join(root, "packaging/signing.json"))
	if err != nil {
		return config{}, err
	}
	if path == "" {
		path = filepath.Join(root, "signing.local.json")
		if _, err := os.Stat(path); errors.Is(err, os.ErrNotExist) {
			path = filepath.Join(root, "packaging/signing.json")
		}
	}
	c, err := readConfig(path)
	if err != nil {
		return config{}, err
	}
	if c.Profile != "" && !filepath.IsAbs(c.Profile) {
		c.Profile = filepath.Join(filepath.Dir(path), c.Profile)
	}
	if identity != "" {
		c.SignIdentity = identity
	}
	if profile != "" {
		c.Profile = profile
	}
	if c.Profile != "" {
		c.Profile, err = filepath.Abs(c.Profile)
		if err != nil {
			return config{}, err
		}
	}
	if mode == "" {
		mode = "final"
	}
	if err := c.validate(mode, official); err != nil {
		return config{}, err
	}
	return c, nil
}

func run() error {
	root := flag.String("root", ".", "source root")
	flag.Parse()
	c, err := loadBuildConfig(*root, os.Getenv("PASU_SIGNING_CONFIG"), os.Getenv("PASU_SIGN_IDENTITY"), os.Getenv("PASU_PROFILE"), os.Getenv("PASU_RELEASE_MODE"))
	if err != nil {
		return err
	}
	return generate(*root, c)
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "서명 설정:", err)
		os.Exit(1)
	}
}
