#!/bin/zsh
set -euo pipefail
cd "${0:a:h}"
export PATH="/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/bin"

go run ./scripts/signing-config

V=$(<VERSION)
export CLANG_MODULE_CACHE_PATH="${TMPDIR:-/tmp}/pasu-v2-clang-cache"
export SWIFT_MODULECACHE_PATH="${TMPDIR:-/tmp}/pasu-v2-swift-cache"
# Swift 컴포넌트(Data Protection Keychain + legacy sewrap 이전)를 정적
# 라이브러리로 먼저 빌드한다 — cgo가 링크하므로 go build/test 전에 필요.
swift_flags=()
[[ "${PASU_RELEASE_MODE:-final}" == migration ]] && swift_flags+=(-D PASU_KEYCHAIN_MIGRATION)
xcrun swiftc "${swift_flags[@]}" -O -parse-as-library -emit-library -static -module-name pasuse \
	-o libpasuse.a .build/signing/Identity.swift sewrap_darwin.swift keychain_darwin.swift keychain_group_darwin.swift
# Go's cache does not track changes inside an external static library. Make
# the exact Swift archive a package input so builds AND tests relink it.
swift_digest=$(shasum -a 256 libpasuse.a | awk '{print $1}')
cat > swift_build_stamp.go <<EOF
// Code generated by build.sh; DO NOT EDIT.
package main

const swiftLibrarySHA256 = "$swift_digest"
EOF
go build -trimpath -buildvcs=false -ldflags "-X main.version=$V" -o pasu .
codesign --force --sign - --options runtime pasu
codesign --verify --strict pasu
xcrun swiftc -swift-version 5 -parse-as-library -O \
	-framework SwiftUI -framework AppKit -framework Security -framework ServiceManagement -lbsm \
	-o PasuGUI .build/signing/Identity.swift gui/*.swift
codesign --force --sign - --options runtime PasuGUI
codesign --verify --strict PasuGUI
SIG_INFO=$(codesign --display --verbose=4 pasu 2>&1)
if [[ "$SIG_INFO" != *"runtime"* ]]; then
	echo "오류: hardened runtime 서명 플래그가 없음" >&2
	echo "$SIG_INFO" >&2
	exit 1
fi
GUI_SIG_INFO=$(codesign --display --verbose=4 PasuGUI 2>&1)
if [[ "$GUI_SIG_INFO" != *"runtime"* ]]; then
	echo "오류: GUI hardened runtime 서명 플래그가 없음" >&2
	echo "$GUI_SIG_INFO" >&2
	exit 1
fi
echo "빌드 완료: pasu $V"
echo "$SIG_INFO" | grep -E 'flags='
echo "$GUI_SIG_INFO" | grep -E 'flags='
